[package]
name = "typeattack"
version = "0.1.0-SNAPSHOT"
authors = ["AndreÌ Tietz <andre.tietz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
log = "0.4.11"
rand = "0.7.3"
crossterm = { version = "0.18.0", features = ["event-stream"] }
futures = "0.3.6"
async-std = { version = "1.6.5", features = ["attributes", "unstable"] }